config/routes.rb
Scratch::Application.routes.draw do

  get "angular/index"

  resources :elections



end

app/models/election.rb
class Election < ActiveRecord::Base
  attr_accessible :election_type, :name, :year
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  # GET /elections
  # GET /elections.json
  def index
    @elections = Election.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elections }
    end
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
    @election = Election.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @election }
    end
  end

  # GET /elections/new
  # GET /elections/new.json
  def new
    @election = Election.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @election }
    end
  end

  # GET /elections/1/edit
  def edit
    @election = Election.find(params[:id])
  end

  # POST /elections
  # POST /elections.json
  def create
    @election = Election.new(params[:election])

    respond_to do |format|
      if @election.save
        format.html { redirect_to @election, notice: 'Election was successfully created.' }
        format.json { render json: @election, status: :created, location: @election }
      else
        format.html { render action: "new" }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elections/1
  # PUT /elections/1.json
  def update
    @election = Election.find(params[:id])

    respond_to do |format|
      if @election.update_attributes(params[:election])
        format.html { redirect_to @election, notice: 'Election was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election = Election.find(params[:id])
    @election.destroy

    respond_to do |format|
      format.html { redirect_to elections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/angular_helper.rb
module AngularHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/views/angular/index.html.erb
<!DOCTYPE html>
<html xmlns:ng="http://angularjs.org">
<head>
  <!-- the following enables Google Chrome Frame, see also below: conditional inclusion for IE older than 7 -->
  <meta http-equiv="X-UA-Compatible" content="chrome=1">

  <title>Experimenting for DACS - Angularjs and selecting a list</title>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js"></script>
  <script type="text/javascript" src="/javascripts/app.js"></script>
</head>
<body>

<!--[if lt IE 8]>
<p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
<![endif]-->

<p>Just a test...</p>

<div id="ng:app" class="ng-app" ng-app="selectListApp">
  <p>I am nominating myself for</p>
  <div ng-controller="SelectListCtrl">

    <!-- We should have one radio button checked initially (see http://www.w3.org/TR/html401/interact/forms.html#radio), but we hide it, as unnecessary for the user: -->
    <input type="radio" name="upcomingOrRevisionGroup" ng-hide="true" checked>
    <input type="radio" name="upcomingOrRevisionGroup" ng-click="setUpcoming(true)">An upcoming election
    <input type="radio" name="upcomingOrRevisionGroup" ng-click="setUpcoming(false)">A list revision

    <hr/>

    <div ng-show="wantsUpcomingElection">
      <div>
        <select ng-model="selectedUpcomingElection" ng-options="e.name for e in upcomingElections" ng-change="updateRegionalityControls()">
          <option value="">Choose an election...</option>
        </select>
        <select ng-model="selectedElectionType" ng-options="type.name for type in electionTypes" ng-change="updateRegionalityControls()">
          <option value="">Choose an election type...</option>
        </select>
      </div>

      <div ng-show="upcomingRegionality">
        ... now select province, region, municipality, and maybe ward.
      </div>
    </div>

    <p ng-show="wantsListRevision">
      Show something about list revisions
    </p>

    <hr/>
    DEBUG: What's the state in the controller:
    wantsUpcomingElection={{wantsUpcomingElection}}
    selectedUpcomingElection={{selectedUpcomingElection}}
    selectedElectionType={{selectedElectionType}}
  </div>
</div>

</body>
</html>

app/views/elections/_form.html.erb
<%= form_for(@election) do |f| %>
  <% if @election.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@election.errors.count, "error") %> prohibited this election from being saved:</h2>

      <ul>
      <% @election.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :election_type %><br />
    <%= f.text_field :election_type %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elections/edit.html.erb
<h1>Editing election</h1>

<%= render 'form' %>

<%= link_to 'Show', @election %> |
<%= link_to 'Back', elections_path %>

app/views/elections/index.html.erb
<h1>Listing elections</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Election type</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elections.each do |election| %>
  <tr>
    <td><%= election.name %></td>
    <td><%= election.election_type %></td>
    <td><%= election.year %></td>
    <td><%= link_to 'Show', election %></td>
    <td><%= link_to 'Edit', edit_election_path(election) %></td>
    <td><%= link_to 'Destroy', election, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Election', new_election_path %>

app/views/elections/new.html.erb
<h1>New election</h1>

<%= render 'form' %>

<%= link_to 'Back', elections_path %>

app/views/elections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @election.name %>
</p>

<p>
  <b>Election type:</b>
  <%= @election.election_type %>
</p>

<p>
  <b>Year:</b>
  <%= @election.year %>
</p>


<%= link_to 'Edit', edit_election_path(@election) %> |
<%= link_to 'Back', elections_path %>

app/views/layouts/application.html.erb
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
  <!--<title>Scratch</title>-->
  <!--<%= stylesheet_link_tag    "application", :media => "all" %>-->
  <!--<%= javascript_include_tag "application" %>-->
  <!--<%= csrf_meta_tags %>-->
<!--</head>-->
<!--<body>-->

<!--<%= yield %>-->

<!--</body>-->
<!--</html>-->